export default {
    rows: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rows.png',
    vert: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/vert.png',
    add: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/add.png',
    top: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/top.png',
    arrow_top: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/arrow_top.png',
    arrow_bt: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/arrow_bt.png',
    filtrate: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/filtrate.png',
    arrow_right: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/arrow_right.png',
    pay_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/pay_icon.png',
    star: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/star.png',
    dete_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/dete_icon.png',
    smeil_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/smeil_icon.png',
    heart_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/heart_icon.png',
    msg_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/msg_icon.png',
    per_icon: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/per_icon.png',
    praise: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/praise.png',
    star_full: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/star_full.png',
    search: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/search.png',
    gou: 'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/gou.png',
    gift:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/gift.png',
    playing:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/playing.png',
    gold_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/gold_icon.png',
    onpraise:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/onpraise.png',
    cate_full:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cate_full.png',
    cate:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cate.png',
    home_full:require('../asset/home_full.png'),
    home:require('../asset/home.png'),
    study_full:require('../asset/study_full.png'),
    study:require('../asset/study.png'),
    user_full:require('../asset/user_full.png'),
    user:require('../asset/user.png'),
    find_full:require('../asset/find_full.png'),
    find:require('../asset/find.png'),
    collected:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/collected.png',
    edit:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/edit.png',
    vipleves:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/vipleves.png',
    g_breath:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/g_breath.png',
    g_filp:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/g_filp.png',
    g_hot:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/g_hot.png',
    g_share:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/g_share.png',
    r_rank:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/r_rank.png',
    c_gift:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/c_gift.png',
    radio:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/radio.png',
    radio_full:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/radio_full.png',
    rank_fir:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rank_fir.png',
    rank_sec:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rank_sec.png',
    rank_thr:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rank_thr.png',
    i_dete:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/i_dete.png',
    right_arrow:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/right_arrow.png',
    update_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/update_icon.png',
    cover_tips_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cover_tips_icon.png',
    cate_new_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cate_new_icon.png',
    halfstar:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/halfstar.png',
    lv0:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/lv0.png',
    auth_iocn:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/auth_iocn.png',
    headertit:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/headertit.png',
    goldtip:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/goldtip.png',
    tip_dele:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/tip_dele.png',
    collect_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/collect_icon.png',
    evals_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/evals_icon.png',
    istop:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/istop.png',
    uppic:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/uppic.png',
    fullScreen:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/fullScreen.png',
    smallScreen:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/smallScreen.png',
    view_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/view_icon.png',


    aud_next:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/aud_next.png',
    aud_pause:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/aud_pause.png',
    aud_pre:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/aud_pre.png',
    aud_speed:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/aud_speed.png',
    aud_list:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/audioList.png',
    aud_pay:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/aud_pay.jpg',
    emjio_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/emjio_icon.png',
    eval_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/eval_icon.png',
    audioing:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/audioing.png',

    video_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/video_icon.png',
    share_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/share_icon.png',
    ct_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/ct_icon.png',

    
    video_close:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/video_close.png',

    train_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/train_icon.png',
    audio_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/audio_icon.png',
    mail_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/mail_icon.png',
    liveBack_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/liveBack_icon.png',
    pk_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/pk_icon.png',

    
    cate_h_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cate_h_icon.png',


    cmic_beg:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cmic_beg.png',
    cmic_parse:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/cmic_parse.png',

    study_bg:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/study_bg.png',

    learn_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/learn_icon.png',


    study_course:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/study_course.png',
    study_hour:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/study_hour.png',
    study_total:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/study_total.png',

    sheet:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/sheet.png',


    check_full:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/check_full.png',
    check:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/check.png',
    select_full:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/f_select.png',
    select:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/select.png',

    lect_da:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/lect_da.png',

    share_r_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/share_r_icon.png',
    pass_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/pass_icon.jpg',

    lect_fail:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/lect_fail.jpg',
    lect_null:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/lect_null.jpg',


    ali_pay:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/ali_pay.png',
    caedit_pay:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/caedit_pay.png',
    wechat_pay:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/wechat_pay.png',

    adminIcon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/adminIcon.png',
    newsIcon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/newsIcon.png',
    reminIcon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/reminIcon.png',
    sysIcon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/sysIcon.png',

    up_video:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/up_video.png',


    firends_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/firends_icon.png',
    wechat_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/wechat_icon.png',

    user_accout:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_accout.png',
    user_cert:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_cert.png',
    user_const:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_const.png',
    user_coupon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_coupon.png',
    user_footer:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_footer.png',
    user_lucky:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_lucky.png',
    user_reward:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_reward.png',
    user_studydata:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_studydata.png',
    user_woods:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_woods.png',

    user_collect:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_collect.png',
    user_focus:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_focus.png',
    user_hascourse:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_hascourse.png',
    user_intergral:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_intergral.png',

    lg_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/lg_icon.png',
    edit_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/edit_icon.png',

    rech_icon1:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rech_icon1.png',
    rech_icon2:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rech_icon2.png',
    rech_icon3:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rech_icon3.png',

    btm_actgle:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/btm_actgle.png',
    
    threedot:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/threedot.png',

    list_3:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/list_3.png',
    list_2:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/list_2.png',
    list_1:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/list_1.png',

    left_arrow:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/left_arrow.png',

    add_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/add_icon.png',


    sign_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/sign_icon.png',

    message_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/message_icon.png',
    setting_icon:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/setting_icon.png',
    user_down:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/user_down.png',
    picture_down:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/picture_down.png',
    vant:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/vant.png',
    share_atlas:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/share_atlas.png',
    download:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/download.png',
    vant_white:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/vant_white.png',
    fanpaia:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/card_fan.png',
    shares:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/shares.png',
    share_w:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/share_w.png',
    rights:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/rights.png',
    bofang:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/bofang.png',
    bofang_t:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/bofang_t.png',
    jia:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/jia.png',
    unvant:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/unvant.png',
    left_a:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/left_a.png',
    right_a:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/right_a.png',
    close_w:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/close_w.png',
    bang:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/app/v2/asset/bang.png',
    right_w:'https://i.loli.net/2021/06/28/GFlWhf9TdJ5MyIv.png',
    preasent:'https://i.loli.net/2021/06/28/9PGZLnj3irzDbwE.png',
    aixing:"https://i.loli.net/2021/06/26/dAkvyb48SaZCNuD.png",
    shops:'https://i.loli.net/2021/06/26/otwJuqVl562d1IZ.png',
    present_w:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/a63ec852-d6e8-437c-84d2-54634bc3d7b1.png',
    clocks:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1651821163191.png',
    backg:'https://i.loli.net/2021/06/26/R4VnIEWs8wyhoxv.png',
    bofangtubiao:'https://i.loli.net/2021/07/05/nIPxOrUesME7YRc.png',
    kaoshi:'https://i.loli.net/2021/07/05/MspVn8JUrzhlLko.png',
    leijikecheng:'https://i.loli.net/2021/07/05/w2ipodPIUKlCstS.png',
    yonghutu:'https://i.loli.net/2021/07/05/yqESBbhwgIlAoP7.png',
    pinfeng:'https://i.loli.net/2021/07/05/G3ipyPrhtmM9KRB.png',
    kecheng:'https://i.loli.net/2021/07/05/xBRdeq3sQ6n1ONW.png',
    xinqin:'https://i.loli.net/2021/07/05/R1gGlTaBfK7NC54.png',
    dashang:'https://i.loli.net/2021/07/05/uMYLjqRxfktrZpG.png',
    // close_w:'https://i.loli.net/2021/07/14/A9Ecae2vzlmMUyD.png',
    prize_ic:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/c06a3b61-f220-47d0-bccc-45166691de97.png',
    vant_on:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197743276.png',
    back_w:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197750172.png',
    right_or:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197760495.png',
    posts:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197777033.png',
    likess:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197787980.png',
    likess_o:'https://edu-uat.oss-cn-shenzhen.aliyuncs.com/images/1653197795956.png',
    moneygif:'https://i.loli.net/2021/07/26/sE6hgyFeDtbmcPN.gif',
    dianzangif:'https://i.loli.net/2021/07/26/QnEtBDrMdv5SuhL.gif',
}